#!/bin/bash
## jxpx @ 2024

TopLeft=`cat $HOME/.dzen2-screencorners | grep -e "tl\\*" | grep -e "nop" -v | sed 's/tl\*//g' | paste - -s -d ';'` && echo "'$TopLeft'" | dzen2 -title-name dzen2-TopLeft -p -m -w 1 -h 1 -x 0 -y 0 -e "$TopLeft" &
BottomLeft=`cat $HOME/.dzen2-screencorners | grep -e "bl\\*" | grep -e "nop" -v | sed 's/bl\*//g' | paste - -s -d ';'` && echo "'$BottomLeft'" | dzen2 -title-name dzen2-BottomLeft -p -m -w 1 -h 1 -x 0 -y -1 -e "$BottomLeft" &
TopRight=`cat $HOME/.dzen2-screencorners | grep -e "tr\\*" | grep -e "nop" -v | sed 's/tr\*//g' | paste - -s -d ';'` && echo "'$TopRight'" | dzen2 -title-name dzen2-TopRight -p -m -w 1 -h 1 -x -1 -y 0 -e "$TopRight" &
BottomRight=`cat $HOME/.dzen2-screencorners | grep -e "br\\*" | grep -e "nop" -v | sed 's/br\*//g' | paste - -s -d ';'` && echo "'$BottomRight'" | dzen2 -title-name dzen2-BottomRight -p -m -w 1 -h 1 -x -1 -y -1 -e "$BottomRight" &
